DROP PROCEDURE IF EXISTS update_lesson(TEXT, TEXT, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS get_chapter(TEXT, TEXT, INTEGER);
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS federated_credentials;
DROP TABLE IF EXISTS assets;
